import type { Database } from "./types";

export const seed: Database = {
  users: [
    {
      id: "u-1",
      name: "Medical Superintendent Office",
      username: "admin",
      password: "admin123",
      role: "admin",
      department: "Hospital Administration",
      email: "ms.ash@kmc.gos.pk",
      phone: "021-99260301",
    },
    {
      id: "u-2",
      name: "Prof. Dr. Muhammad Nadeem",
      username: "doctor",
      password: "doctor123",
      role: "doctor",
      department: "Internal Medicine",
      email: "dr.nadeem@ash.org.pk",
      phone: "0300-9281720",
    },
    {
      id: "u-3",
      name: "Sana Farhan",
      username: "reception",
      password: "rec123",
      role: "receptionist",
      department: "Central OPD Registration",
      email: "reception.opd@ash.org.pk",
      phone: "021-99260305",
    },
    {
      id: "u-4",
      name: "Muhammad Imran Ali",
      username: "pharmacy",
      password: "pharma123",
      role: "pharmacist",
      department: "Main Hospital Pharmacy",
      email: "pharmacy@ash.org.pk",
      phone: "021-99260312",
    },
    {
      id: "u-5",
      name: "Sister Fatima Zahra",
      username: "nurse",
      password: "nurse123",
      role: "nurse",
      department: "Emergency & Trauma Triage",
      email: "emergency.nursing@ash.org.pk",
      phone: "021-99260319",
    },
    {
      id: "u-6",
      name: "Muhammad Zubair Siddiqui",
      username: "labtech",
      password: "lab123",
      role: "lab_technician",
      department: "Central Pathology Laboratory",
      email: "pathology@ash.org.pk",
      phone: "021-99260314",
    },
  ],

  patients: [
    {
      id: "p-1",
      mrn: "ASH-10021",
      name: "Muhammad Bilal Khan",
      gender: "Male",
      age: 42,
      dob: "1984-06-14",
      phone: "0300-5552141",
      cnic: "42101-1234567-1",
      guardianName: "Abdul Rasheed Khan (Father)",
      emergencyContact: "0333-8889911 (Wife - Sadia Bilal)",
      address: "Block H, North Nazimabad, Karachi",
      bloodGroup: "B+",
      allergies: "Penicillin, Sulfa drugs",
      chronicConditions: "Hypertension (Stage 2), Type 2 Diabetes",
      panelType: "Sehat Sahulat",
      status: "Outpatient",
      vitals: {
        bp: "145/92",
        pulse: 78,
        temperature: 98.6,
        spO2: 98,
        respiratoryRate: 16,
        weight: 76,
        height: 172,
        bmi: 25.7,
        bloodSugar: 142,
        recordedAt: "2026-09-28 09:30",
      },
      registeredAt: "2026-03-12",
    },
    {
      id: "p-2",
      mrn: "ASH-10022",
      name: "Fatima Noor",
      gender: "Female",
      age: 29,
      dob: "1997-02-18",
      phone: "0321-8891200",
      cnic: "42101-7654321-2",
      guardianName: "Muhammad Zahid Noor (Husband)",
      emergencyContact: "0321-8891201",
      address: "Sector 15-A, Buffer Zone, Karachi",
      bloodGroup: "O+",
      allergies: "None",
      chronicConditions: "G1P0, 28 Weeks Gestation",
      panelType: "KMC Staff",
      status: "Outpatient",
      vitals: {
        bp: "115/75",
        pulse: 82,
        temperature: 98.4,
        spO2: 99,
        respiratoryRate: 18,
        weight: 64,
        height: 160,
        bmi: 25.0,
        bloodSugar: 98,
        recordedAt: "2026-09-28 10:15",
      },
      registeredAt: "2026-05-02",
    },
    {
      id: "p-3",
      mrn: "ASH-10023",
      name: "Ahmed Raza Qureshi",
      gender: "Male",
      age: 67,
      dob: "1959-11-05",
      phone: "0333-4412098",
      cnic: "42101-9988776-3",
      guardianName: "Kamran Raza Qureshi (Son)",
      emergencyContact: "0333-4412099",
      address: "Block 14, Federal B Area, Karachi",
      bloodGroup: "A+",
      allergies: "Aspirin (Causes Gastritis)",
      chronicConditions: "Coronary Artery Disease, Dyslipidemia",
      panelType: "Indigent/Free",
      status: "Admitted",
      vitals: {
        bp: "155/95",
        pulse: 88,
        temperature: 99.1,
        spO2: 95,
        respiratoryRate: 20,
        weight: 82,
        height: 168,
        bmi: 29.1,
        bloodSugar: 180,
        recordedAt: "2026-09-28 08:00",
      },
      registeredAt: "2025-11-18",
    },
    {
      id: "p-4",
      mrn: "ASH-10024",
      name: "Hina Farhan Sheikh",
      gender: "Female",
      age: 8,
      dob: "2018-08-10",
      phone: "0312-2201987",
      cnic: "42101-3344556-4",
      guardianName: "Muhammad Farhan Sheikh (Father)",
      emergencyContact: "0312-2201987",
      address: "Paposh Nagar, Nazimabad, Karachi",
      bloodGroup: "AB+",
      allergies: "None known",
      chronicConditions: "Recurrent tonsillitis",
      panelType: "Private",
      status: "Outpatient",
      vitals: {
        bp: "100/65",
        pulse: 104,
        temperature: 102.3,
        spO2: 98,
        respiratoryRate: 24,
        weight: 24,
        height: 122,
        bmi: 16.1,
        recordedAt: "2026-09-28 09:00",
      },
      registeredAt: "2026-08-21",
    },
    {
      id: "p-5",
      mrn: "ASH-10025",
      name: "Zainab Hussain",
      gender: "Female",
      age: 54,
      dob: "1972-04-12",
      phone: "0345-6677889",
      cnic: "42101-1122334-5",
      guardianName: "Altaf Hussain (Husband)",
      emergencyContact: "0345-6677889",
      address: "Nazimabad No. 4, Karachi",
      bloodGroup: "O-",
      allergies: "Ciprofloxacin, NSAIDs",
      chronicConditions: "Osteoarthritis Bilateral Knees, Osteopenia",
      panelType: "Sehat Sahulat",
      status: "Outpatient",
      vitals: {
        bp: "130/85",
        pulse: 74,
        temperature: 98.4,
        spO2: 98,
        respiratoryRate: 16,
        weight: 71,
        height: 155,
        bmi: 29.5,
        recordedAt: "2026-09-27 12:30",
      },
      registeredAt: "2026-01-09",
    },
    {
      id: "p-6",
      mrn: "ASH-10026",
      name: "Muhammad Usman Ghani",
      gender: "Male",
      age: 35,
      dob: "1991-09-15",
      phone: "0308-1122334",
      cnic: "42101-5566778-6",
      guardianName: "Haji Muhammad Ghani (Father)",
      emergencyContact: "0308-9988112",
      address: "Block 7, Gulberg Town, Karachi",
      bloodGroup: "B-",
      allergies: "None",
      chronicConditions: "None",
      panelType: "Private",
      status: "Emergency",
      vitals: {
        bp: "110/70",
        pulse: 112,
        temperature: 103.1,
        spO2: 97,
        respiratoryRate: 22,
        weight: 68,
        height: 175,
        bmi: 22.2,
        bloodSugar: 110,
        recordedAt: "2026-09-28 11:20",
      },
      registeredAt: "2026-09-01",
    },
    {
      id: "p-7",
      mrn: "ASH-10027",
      name: "Rashida Begum",
      gender: "Female",
      age: 61,
      dob: "1965-03-22",
      phone: "0315-7766554",
      cnic: "42101-8877665-7",
      guardianName: "Muhammad Tariq Beg (Son)",
      emergencyContact: "0315-7766554",
      address: "Liaquatabad Block 4, Karachi",
      bloodGroup: "AB-",
      allergies: "Dust, Erythromycin",
      chronicConditions: "COPD, Bronchial Asthma",
      panelType: "Indigent/Free",
      status: "Admitted",
      vitals: {
        bp: "138/88",
        pulse: 92,
        temperature: 99.0,
        spO2: 91,
        respiratoryRate: 26,
        weight: 58,
        height: 152,
        bmi: 25.1,
        recordedAt: "2026-09-28 07:45",
      },
      registeredAt: "2026-02-14",
    },
    {
      id: "p-8",
      mrn: "ASH-10028",
      name: "Muhammad Arsalan",
      gender: "Male",
      age: 24,
      dob: "2002-05-10",
      phone: "0334-1234567",
      cnic: "42101-6677889-8",
      guardianName: "Muhammad Aslam (Father)",
      emergencyContact: "0334-1234567",
      address: "Malir Colony, Karachi",
      bloodGroup: "O+",
      allergies: "None",
      chronicConditions: "None",
      panelType: "Sehat Sahulat",
      status: "Outpatient",
      vitals: {
        bp: "120/80",
        pulse: 72,
        temperature: 98.4,
        spO2: 99,
        respiratoryRate: 16,
        weight: 65,
        height: 173,
        bmi: 21.7,
        recordedAt: "2026-09-28 09:10",
      },
      registeredAt: "2026-09-10",
    },
    {
      id: "p-9",
      mrn: "ASH-10029",
      name: "Ayesha Siddiqa",
      gender: "Female",
      age: 38,
      dob: "1988-08-14",
      phone: "0322-9876543",
      cnic: "42101-4455667-9",
      guardianName: "Tariq Mahmood Siddiqui (Husband)",
      emergencyContact: "0322-9876543",
      address: "PECHS Block 2, Karachi",
      bloodGroup: "A-",
      allergies: "Sulfa",
      chronicConditions: "Migraine, Hypothyroidism",
      panelType: "Private",
      status: "Outpatient",
      vitals: {
        bp: "125/82",
        pulse: 76,
        temperature: 98.6,
        spO2: 98,
        respiratoryRate: 18,
        weight: 62,
        height: 158,
        bmi: 24.8,
        recordedAt: "2026-09-28 10:00",
      },
      registeredAt: "2026-08-05",
    },
    {
      id: "p-10",
      mrn: "ASH-10030",
      name: "Haji Abdul Samad",
      gender: "Male",
      age: 72,
      dob: "1954-01-01",
      phone: "0346-5544332",
      cnic: "42101-2233445-0",
      guardianName: "Muhammad Imran Samad (Son)",
      emergencyContact: "0346-5544332",
      address: "Shadman Town, Sector 14-B, Karachi",
      bloodGroup: "B+",
      allergies: "None",
      chronicConditions: "Benign Prostatic Hyperplasia, Hypertension",
      panelType: "Indigent/Free",
      status: "Outpatient",
      vitals: {
        bp: "140/90",
        pulse: 70,
        temperature: 98.2,
        spO2: 97,
        respiratoryRate: 16,
        weight: 70,
        height: 165,
        bmi: 25.7,
        recordedAt: "2026-09-28 10:45",
      },
      registeredAt: "2026-09-15",
    },
  ],

  doctors: [
    {
      id: "d-1",
      name: "Prof. Dr. Muhammad Nadeem",
      specialty: "Professor & Head of Internal Medicine",
      department: "Internal Medicine",
      qualification: "MBBS, FCPS (Medicine), FRCP (Glasg), FACP (USA)",
      pmdcReg: "PMC-12948-S",
      roomNo: "Executive OPD Clinic #01 (Ground Floor)",
      phone: "021-99260400",
      email: "dr.nadeem@ash.org.pk",
      days: "Mon, Tue, Wed, Thu, Fri, Sat",
      timing: "08:30 AM – 02:00 PM",
      fee: 200,
      maxDailyTokens: 50,
      status: "In OPD",
    },
    {
      id: "d-2",
      name: "Dr. Muhammad Tariq",
      specialty: "Associate Professor of General & Laparoscopic Surgery",
      department: "General Surgery",
      qualification: "MBBS, MS (Surgery), FCPS (Surgery), FACS",
      pmdcReg: "PMC-18230-S",
      roomNo: "Surgical OPD Clinic #05 (1st Floor)",
      phone: "021-99260401",
      email: "dr.tariq@ash.org.pk",
      days: "Mon, Wed, Fri",
      timing: "09:00 AM – 02:30 PM",
      fee: 200,
      maxDailyTokens: 40,
      status: "In Surgery",
    },
    {
      id: "d-3",
      name: "Dr. Samina Nadeem",
      specialty: "Consultant Obstetrician & Gynecologist",
      department: "Gynae & Obs",
      qualification: "MBBS, FCPS (Gynae/Obs), MRCOG (UK)",
      pmdcReg: "PMC-21940-S",
      roomNo: "Gynae Wing OPD #02",
      phone: "021-99260402",
      email: "dr.samina@ash.org.pk",
      days: "Tue, Thu, Sat",
      timing: "09:00 AM – 01:30 PM",
      fee: 200,
      maxDailyTokens: 45,
      status: "Available",
    },
    {
      id: "d-4",
      name: "Dr. Muhammad Kamran",
      specialty: "Consultant Orthopedic & Trauma Surgeon",
      department: "Orthopedics & Trauma",
      qualification: "MBBS, FCPS (Orthopedics), AO Trauma Fellow",
      pmdcReg: "PMC-14502-S",
      roomNo: "Orthopedic Clinic #08 (Ground Floor)",
      phone: "021-99260403",
      email: "dr.kamran@ash.org.pk",
      days: "Mon, Tue, Thu, Fri",
      timing: "10:00 AM – 03:00 PM",
      fee: 200,
      maxDailyTokens: 35,
      status: "Available",
    },
    {
      id: "d-5",
      name: "Dr. Asma Bilal",
      specialty: "Associate Professor of Pediatrics & Neonatology",
      department: "Pediatrics & Neonatology",
      qualification: "MBBS, DCH, FCPS (Pediatrics)",
      pmdcReg: "PMC-23819-S",
      roomNo: "Pediatric OPD Clinic #01",
      phone: "021-99260404",
      email: "dr.asma@ash.org.pk",
      days: "Mon to Sat",
      timing: "08:30 AM – 01:30 PM",
      fee: 150,
      maxDailyTokens: 60,
      status: "In OPD",
    },
    {
      id: "d-6",
      name: "Dr. Muhammad Farooq",
      specialty: "Consultant Interventional Cardiologist",
      department: "Cardiology & CCU",
      qualification: "MBBS, FCPS (Cardiology), Dip. Interventional",
      pmdcReg: "PMC-11094-S",
      roomNo: "Cardiology Center OPD #03",
      phone: "021-99260405",
      email: "dr.farooq@ash.org.pk",
      days: "Wed, Thu, Fri, Sat",
      timing: "10:00 AM – 02:00 PM",
      fee: 300,
      maxDailyTokens: 30,
      status: "Available",
    },
    {
      id: "d-7",
      name: "Dr. Muhammad Asim",
      specialty: "In-charge Emergency & Resuscitation",
      department: "Emergency Medicine",
      qualification: "MBBS, MRCEM (UK)",
      pmdcReg: "PMC-29401-S",
      roomNo: "Trauma Center ER Bay A",
      phone: "021-99260409",
      email: "dr.asim@ash.org.pk",
      days: "24/7 Rota",
      timing: "Round the Clock Shift",
      fee: 100,
      maxDailyTokens: 100,
      status: "Available",
    },
  ],

  appointments: [
    {
      id: "a-1",
      tokenNo: "OPD-MED-001",
      patientId: "p-1",
      doctorId: "d-1",
      date: "2026-09-28",
      time: "09:30 AM",
      department: "Internal Medicine",
      reason: "Follow-up for uncontrolled BP & fasting blood glucose review with Prof. Dr. Muhammad Nadeem",
      status: "In-Consultation",
      priority: "Normal",
      notes: "Previous Rx Amlodipine 5mg OD not fully managing BP (145/92 today). Advised combination therapy.",
    },
    {
      id: "a-2",
      tokenNo: "OPD-GYN-003",
      patientId: "p-2",
      doctorId: "d-3",
      date: "2026-09-28",
      time: "10:15 AM",
      department: "Gynae & Obs",
      reason: "Antenatal Checkup 28 Weeks & Anomaly Scan Review with Dr. Samina Nadeem",
      status: "Checked-in",
      priority: "Normal",
      notes: "Fetal movements good. Mild ankle edema.",
    },
    {
      id: "a-3",
      tokenNo: "OPD-PED-002",
      patientId: "p-4",
      doctorId: "d-5",
      date: "2026-09-28",
      time: "09:00 AM",
      department: "Pediatrics & Neonatology",
      reason: "High grade fever (102.3°F), sore throat, poor oral intake",
      status: "Completed",
      priority: "Urgent",
      notes: "Diagnosed tonsillopharyngitis. Antibiotic syrup prescribed.",
    },
    {
      id: "a-4",
      tokenNo: "OPD-CARD-001",
      patientId: "p-3",
      doctorId: "d-6",
      date: "2026-09-28",
      time: "11:30 AM",
      department: "Cardiology & CCU",
      reason: "Post-admission cardiac review & Echo report evaluation",
      status: "Scheduled",
      priority: "Urgent",
      notes: "Patient admitted in CCU Bed #02. Doctor to visit ward.",
    },
    {
      id: "a-5",
      tokenNo: "OPD-ORTHO-004",
      patientId: "p-5",
      doctorId: "d-4",
      date: "2026-09-29",
      time: "10:30 AM",
      department: "Orthopedics & Trauma",
      reason: "Bilateral knee joint pain & review of Knee X-Ray (AP/Lat)",
      status: "Scheduled",
      priority: "Normal",
    },
    {
      id: "a-6",
      tokenNo: "OPD-MED-002",
      patientId: "p-8",
      doctorId: "d-1",
      date: "2026-09-28",
      time: "12:00 PM",
      department: "Internal Medicine",
      reason: "General medical checkup and fitness certificate with Prof. Dr. Muhammad Nadeem",
      status: "Scheduled",
      priority: "Normal",
    },
  ],

  records: [
    {
      id: "r-1",
      patientId: "p-1",
      doctorId: "d-1",
      date: "2026-09-28",
      time: "09:30 AM",
      chiefComplaint: "Morning headache, dizziness, BP 145/92, uncontrolled fasting sugar (142 mg/dL)",
      history: "42 y/o executive with 4-year history of hypertension and Type 2 Diabetes. Non-smoker. Complains of mild exertional fatigue.",
      examination: "General: Well oriented, no pallor/cyanosis. CVS: S1+S2 audible, no murmurs. Chest: Bilateral vesicular breathing. Fundus: Grade 1 Hypertensive Retinopathy.",
      diagnosis: "Essential Hypertension (Stage 2) & Type 2 Diabetes Mellitus (Suboptimal Control)",
      icdCode: "I10 / E11.9",
      vitals: {
        bp: "145/92",
        pulse: 78,
        temperature: 98.6,
        spO2: 98,
        recordedAt: "2026-09-28 09:30",
      },
      prescription: [
        {
          medicineId: "m-2",
          medicineName: "Amlodipine + Valsartan 5mg/80mg (Exforge)",
          dosage: "1 Tab",
          frequency: "OD (Once daily morning after breakfast)",
          duration: "30 days",
          instructions: "Maintain home BP log twice weekly. Avoid adding raw salt.",
        },
        {
          medicineId: "m-8",
          medicineName: "Metformin 500mg (Glucophage)",
          dosage: "500mg",
          frequency: "BD (Twice daily with meals)",
          duration: "30 days",
          instructions: "Take with food to minimize GI discomfort.",
        },
      ],
      labOrdersSuggested: ["Serum Creatinine", "Serum Electrolytes", "HbA1c", "Fasting Lipid Profile"],
      notes: "Strict dietary salt restriction (< 5g/day), 30 minutes brisk walking daily. Review with 7-day home BP chart. Consultant: Prof. Dr. Muhammad Nadeem.",
      followUpDate: "2026-10-15",
    },
    {
      id: "r-2",
      patientId: "p-4",
      doctorId: "d-5",
      date: "2026-09-28",
      time: "09:15 AM",
      chiefComplaint: "High grade fever (102.3°F) x 3 days, throat pain, dry cough",
      history: "8 y/o female child with sudden onset fever and painful swallowing. Immunization complete according to EPI schedule.",
      examination: "Throat: Congested pharynx with bilateral tonsillar enlargement and follicular exudates. Chest: Clear bilaterally.",
      diagnosis: "Acute Follicular Tonsillopharyngitis",
      icdCode: "J03.90",
      vitals: {
        bp: "100/65",
        pulse: 104,
        temperature: 102.3,
        spO2: 98,
        recordedAt: "2026-09-28 09:00",
      },
      prescription: [
        {
          medicineId: "m-3",
          medicineName: "Amoxicillin + Clavulanic Acid 312.5mg/5ml Syrup",
          dosage: "5ml",
          frequency: "TDS (Every 8 hours)",
          duration: "7 days",
          instructions: "After meals. Complete full 7-day course.",
        },
        {
          medicineId: "m-1",
          medicineName: "Paracetamol 250mg/5ml Syrup",
          dosage: "7.5ml",
          frequency: "TDS / SOS (When fever > 100°F)",
          duration: "3 days",
          instructions: "Do not exceed 4 doses in 24 hours.",
        },
      ],
      labOrdersSuggested: ["CBC (Complete Blood Count)", "Throat Swab Culture"],
      notes: "Advised warm salt water gargles, soft diet, and abundant fluids. Return to OPD if breathing difficulty develops.",
      followUpDate: "2026-10-05",
    },
    {
      id: "r-3",
      patientId: "p-5",
      doctorId: "d-4",
      date: "2026-09-27",
      time: "11:45 AM",
      chiefComplaint: "Severe pain and stiffness in both knees, worse on stairs and namaz",
      history: "54 y/o female with gradual onset bilateral knee pain over 3 years. Crepitus on movement. Morning stiffness ~20 minutes.",
      examination: "Gait: Antalgic. Knees: Bilateral medial joint line tenderness, bony enlargement, crepitus positive.",
      diagnosis: "Bilateral Primary Osteoarthritis of Knees (Kellgren-Lawrence Grade 3)",
      icdCode: "M17.0",
      vitals: {
        bp: "130/85",
        pulse: 74,
        temperature: 98.4,
        spO2: 98,
        recordedAt: "2026-09-27 12:30",
      },
      prescription: [
        {
          medicineId: "m-6",
          medicineName: "Diclofenac Sodium 50mg Tablet",
          dosage: "50mg",
          frequency: "BD (Twice daily after food)",
          duration: "5 days",
          instructions: "Take strictly after meals with water.",
        },
        {
          medicineId: "m-8",
          medicineName: "Omeprazole 20mg Capsule",
          dosage: "20mg",
          frequency: "OD (Once daily morning before breakfast)",
          duration: "14 days",
          instructions: "Take 30 mins before breakfast.",
        },
      ],
      labOrdersSuggested: ["Bilateral Knee X-Ray (AP & Lateral Weight-bearing)", "Serum Uric Acid"],
      notes: "Referred to ASH Physiotherapy Department for quadriceps strengthening exercises. Advised use of chair for namaz.",
      followUpDate: "2026-10-10",
    },
  ],

  emergencyPatients: [
    {
      id: "er-1",
      patientId: "p-6",
      triageLevel: "Red",
      bedNumber: "ER-Resus-01",
      chiefComplaint: "High fever (103.1°F), severe retro-orbital pain, bleeding gums, petechial rash (Suspected Severe Dengue)",
      vitals: {
        bp: "110/70",
        pulse: 112,
        temperature: 103.1,
        spO2: 97,
        respiratoryRate: 22,
        recordedAt: "2026-09-28 11:20",
      },
      attendingDoctorId: "d-1",
      arrivalTime: "2026-09-28 11:15 AM",
      status: "Treatment",
      notes: "Under supervision of Prof. Dr. Muhammad Nadeem. IV Line 18G secured. IV Ringer Lactate started at 100ml/hr. STAT CBC & Dengue NS1 dispatched.",
    },
    {
      id: "er-2",
      patientId: "p-3",
      triageLevel: "Yellow",
      bedNumber: "ER-Bay-04",
      chiefComplaint: "Retrosternal chest tightness radiating to left shoulder, diaphoresis x 2 hours",
      vitals: {
        bp: "155/95",
        pulse: 88,
        temperature: 99.1,
        spO2: 95,
        respiratoryRate: 20,
        recordedAt: "2026-09-28 08:00",
      },
      attendingDoctorId: "d-6",
      arrivalTime: "2026-09-28 07:45 AM",
      status: "Admitted",
      notes: "STAT ECG showed ST depression in V4-V6. Troponin I elevated (0.84 ng/ml). Transferred to CCU Bed #02.",
    },
    {
      id: "er-3",
      patientId: "p-7",
      triageLevel: "Yellow",
      bedNumber: "ER-Bay-06",
      chiefComplaint: "Acute exacerbation of COPD, severe dyspnea, SpO2 91% on room air",
      vitals: {
        bp: "138/88",
        pulse: 92,
        temperature: 99.0,
        spO2: 91,
        respiratoryRate: 26,
        recordedAt: "2026-09-28 07:45",
      },
      attendingDoctorId: "d-1",
      arrivalTime: "2026-09-28 07:30 AM",
      status: "Admitted",
      notes: "Nebulized with Salbutamol + Ipratropium. IV Hydrocortisone given. Admitted to Female Medical Ward under Prof. Dr. Muhammad Nadeem.",
    },
  ],

  wardBeds: [
    {
      id: "wb-1",
      wardName: "CCU / Coronary Care Unit",
      bedNumber: "CCU-01",
      type: "CCU",
      status: "Available",
      notes: "Defibrillator & multipara monitor checked.",
    },
    {
      id: "wb-2",
      wardName: "CCU / Coronary Care Unit",
      bedNumber: "CCU-02",
      type: "CCU",
      status: "Occupied",
      patientId: "p-3",
      doctorId: "d-6",
      admittedAt: "2026-09-28 08:30 AM",
      notes: "NSTEMI Protocol. Continuous cardiac telemetry.",
    },
    {
      id: "wb-3",
      wardName: "ICU / Intensive Care Unit",
      bedNumber: "ICU-01",
      type: "ICU",
      status: "Occupied",
      patientId: "p-6",
      doctorId: "d-1",
      admittedAt: "2026-09-28 11:45 AM",
      notes: "Dengue Shock monitoring under Prof. Dr. Muhammad Nadeem. Strict I/O charting.",
    },
    {
      id: "wb-4",
      wardName: "ICU / Intensive Care Unit",
      bedNumber: "ICU-02",
      type: "ICU",
      status: "Available",
    },
    {
      id: "wb-5",
      wardName: "Female Medical Ward (Ward 3)",
      bedNumber: "FMW-05",
      type: "General",
      status: "Occupied",
      patientId: "p-7",
      doctorId: "d-1",
      admittedAt: "2026-09-28 08:15 AM",
      notes: "Oxygen via nasal cannula 2 L/min under Prof. Dr. Muhammad Nadeem.",
    },
    {
      id: "wb-6",
      wardName: "Female Medical Ward (Ward 3)",
      bedNumber: "FMW-06",
      type: "General",
      status: "Available",
    },
    {
      id: "wb-7",
      wardName: "Male Medical Ward (Ward 2)",
      bedNumber: "MMW-01",
      type: "General",
      status: "Available",
    },
    {
      id: "wb-8",
      wardName: "Male Medical Ward (Ward 2)",
      bedNumber: "MMW-02",
      type: "General",
      status: "Cleaning",
      notes: "Sanitization in progress after discharge.",
    },
    {
      id: "wb-9",
      wardName: "Emergency Trauma Bays",
      bedNumber: "ER-Resus-01",
      type: "Emergency",
      status: "Occupied",
      patientId: "p-6",
      doctorId: "d-7",
      admittedAt: "2026-09-28 11:15 AM",
    },
    {
      id: "wb-10",
      wardName: "Pediatric Ward (Ward 6)",
      bedNumber: "PED-01",
      type: "Pediatric",
      status: "Available",
    },
  ],

  labOrders: [
    {
      id: "l-1",
      patientId: "p-3",
      doctorId: "d-6",
      test: "Comprehensive Cardiac Panel & Troponin-I",
      category: "Biochemistry",
      orderedAt: "2026-09-28 08:10",
      completedAt: "2026-09-28 09:40",
      status: "Completed",
      results: [
        { name: "Troponin-I (Quantitative)", value: "0.84", unit: "ng/mL", normalRange: "< 0.04", isAbnormal: true },
        { name: "CK-MB", value: "48", unit: "U/L", normalRange: "0 - 25", isAbnormal: true },
        { name: "Total Cholesterol", value: "248", unit: "mg/dL", normalRange: "< 200", isAbnormal: true },
        { name: "Serum Creatinine", value: "1.1", unit: "mg/dL", normalRange: "0.7 - 1.3", isAbnormal: false },
        { name: "Serum Potassium (K+)", value: "4.2", unit: "mEq/L", normalRange: "3.5 - 5.0", isAbnormal: false },
      ],
      doctorNotes: "Elevated Troponin-I and CK-MB consistent with Acute Non-ST Elevation Myocardial Infarction.",
      technicianName: "Muhammad Zubair Siddiqui (Senior MLT)",
    },
    {
      id: "l-2",
      patientId: "p-6",
      doctorId: "d-1",
      test: "STAT Dengue Profile (NS1 Antigen & CBC)",
      category: "Hematology",
      orderedAt: "2026-09-28 11:25",
      completedAt: "2026-09-28 12:05",
      status: "Completed",
      results: [
        { name: "Dengue NS1 Antigen", value: "POSITIVE", unit: "Qualitative", normalRange: "NEGATIVE", isAbnormal: true },
        { name: "Platelet Count", value: "38,000", unit: "/cumm", normalRange: "150,000 - 450,000", isAbnormal: true },
        { name: "Hemoglobin (Hb)", value: "15.8", unit: "g/dL", normalRange: "13.0 - 17.0", isAbnormal: false },
        { name: "Hematocrit (PCV)", value: "48.2", unit: "%", normalRange: "40.0 - 52.0", isAbnormal: false },
        { name: "Total Leukocyte Count (TLC)", value: "2,800", unit: "/cumm", normalRange: "4,000 - 11,000", isAbnormal: true },
      ],
      doctorNotes: "Severe thrombocytopenia (38k) with positive Dengue NS1. Reviewed by Prof. Dr. Muhammad Nadeem.",
      technicianName: "Muhammad Zubair Siddiqui (Senior MLT)",
    },
    {
      id: "l-3",
      patientId: "p-1",
      doctorId: "d-1",
      test: "HbA1c & Fasting Renal Function Panel",
      category: "Biochemistry",
      orderedAt: "2026-09-28 09:45",
      status: "Processing",
      doctorNotes: "Ordered by Prof. Dr. Muhammad Nadeem. Patient fasting 10 hours.",
      technicianName: "Muhammad Zubair Siddiqui (Senior MLT)",
    },
    {
      id: "l-4",
      patientId: "p-2",
      doctorId: "d-3",
      test: "Obstetric Ultrasound (Anomaly Scan)",
      category: "Radiology",
      orderedAt: "2026-09-28 10:20",
      status: "Sample Collected",
      doctorNotes: "Ordered by Dr. Samina Nadeem. Check fetal anatomy, placental localization & liquor index.",
    },
    {
      id: "l-5",
      patientId: "p-5",
      doctorId: "d-4",
      test: "Digital X-Ray Bilateral Knees (AP & Lateral)",
      category: "Radiology",
      orderedAt: "2026-09-27 12:00",
      completedAt: "2026-09-27 12:45",
      status: "Completed",
      results: [
        { name: "Joint Space", value: "Marked medial joint narrowing bilateral", unit: "Visual", normalRange: "Normal space", isAbnormal: true },
        { name: "Osteophytes", value: "Prominent marginal tibial & femoral osteophytes", unit: "Visual", normalRange: "Absent", isAbnormal: true },
        { name: "Subchondral Sclerosis", value: "Present", unit: "Visual", normalRange: "Absent", isAbnormal: true },
      ],
      doctorNotes: "Features diagnostic of Kellgren-Lawrence Grade 3 Osteoarthritis.",
      technicianName: "Muhammad Zubair Siddiqui (Senior MLT)",
    },
  ],

  medicines: [
    {
      id: "m-1",
      name: "Paracetamol 500mg (Panadol)",
      genericName: "Paracetamol / Acetaminophen",
      category: "Analgesic & Antipyretic",
      dosageForm: "Tablet",
      stock: 580,
      minStock: 100,
      unit: "tablets",
      price: 4,
      expiry: "2027-08-31",
      batchNo: "PND-2026-091",
      manufacturer: "GSK Pakistan Ltd",
    },
    {
      id: "m-2",
      name: "Amlodipine 5mg (Norvasc)",
      genericName: "Amlodipine Besylate",
      category: "Cardiovascular / Antihypertensive",
      dosageForm: "Tablet",
      stock: 240,
      minStock: 50,
      unit: "tablets",
      price: 8,
      expiry: "2027-05-15",
      batchNo: "AML-2025-118",
      manufacturer: "Pfizer Pakistan",
    },
    {
      id: "m-3",
      name: "Augmentin 625mg (Amoxi-Clav)",
      genericName: "Amoxicillin + Clavulanic Acid",
      category: "Antibiotics / Penicillins",
      dosageForm: "Tablet",
      stock: 85,
      minStock: 30,
      unit: "tablets",
      price: 32,
      expiry: "2027-02-28",
      batchNo: "AUG-2026-042",
      manufacturer: "GSK Pakistan Ltd",
    },
    {
      id: "m-4",
      name: "ORS (Oral Rehydration Salts Sachet)",
      genericName: "WHO Formula Oral Electrolytes",
      category: "Fluids & Electrolytes",
      dosageForm: "Sachet",
      stock: 14,
      minStock: 50,
      unit: "sachets",
      price: 25,
      expiry: "2027-11-30",
      batchNo: "ORS-2026-015",
      manufacturer: "Searle Company Ltd",
    },
    {
      id: "m-5",
      name: "Insulin 70/30 (Humulin 70/30)",
      genericName: "Human Insulin Isophane / Regular",
      category: "Antidiabetic / Endocrine",
      dosageForm: "Vial (10ml)",
      stock: 9,
      minStock: 25,
      unit: "vials",
      price: 1350,
      expiry: "2026-12-15",
      batchNo: "INS-2025-883",
      manufacturer: "Eli Lilly / Getz Pharma",
    },
    {
      id: "m-6",
      name: "Diclofenac Sodium 50mg (Voltaren)",
      genericName: "Diclofenac Sodium",
      category: "NSAID / Anti-inflammatory",
      dosageForm: "Tablet",
      stock: 310,
      minStock: 60,
      unit: "tablets",
      price: 6,
      expiry: "2027-09-30",
      batchNo: "VOL-2026-302",
      manufacturer: "Novartis Pakistan",
    },
    {
      id: "m-7",
      name: "Ringer Lactate 1000ml IV Infusion",
      genericName: "Sodium Lactate Compound",
      category: "Emergency IV Fluids",
      dosageForm: "IV Bottle",
      stock: 18,
      minStock: 40,
      unit: "bottles",
      price: 120,
      expiry: "2027-10-31",
      batchNo: "RL-2026-551",
      manufacturer: "Otsuka Pakistan",
    },
    {
      id: "m-8",
      name: "Omeprazole 20mg (Risek)",
      genericName: "Omeprazole",
      category: "Gastrointestinal / PPI",
      dosageForm: "Capsule",
      stock: 420,
      minStock: 80,
      unit: "capsules",
      price: 16,
      expiry: "2027-07-20",
      batchNo: "RSK-2026-119",
      manufacturer: "Getz Pharma",
    },
    {
      id: "m-9",
      name: "Ceftriaxone 1g IV Injection (Rocephin)",
      genericName: "Ceftriaxone Sodium",
      category: "Antibiotics / Cephalosporins",
      dosageForm: "Injection",
      stock: 45,
      minStock: 30,
      unit: "vials",
      price: 260,
      expiry: "2027-04-10",
      batchNo: "CEF-2026-701",
      manufacturer: "Ferozsons Laboratories",
    },
    {
      id: "m-10",
      name: "Salbutamol Respirator Solution 5mg/ml",
      genericName: "Salbutamol Sulfate",
      category: "Respiratory / Bronchodilator",
      dosageForm: "Nebulizer Solution (20ml)",
      stock: 12,
      minStock: 20,
      unit: "bottles",
      price: 180,
      expiry: "2026-11-30",
      batchNo: "SLB-2025-412",
      manufacturer: "GlaxoSmithKline",
    },
  ],

  invoices: [
    {
      id: "inv-1",
      invoiceNo: "ASH-INV-2026-0041",
      patientId: "p-4",
      date: "2026-09-28",
      items: [
        { description: "OPD Consultation – Pediatrics (Dr. Asma Bilal)", category: "Consultation", quantity: 1, unitPrice: 150, amount: 150 },
        { description: "Amoxicillin + Clavulanic Acid Syrup 312.5mg", category: "Pharmacy", quantity: 1, unitPrice: 220, amount: 220 },
        { description: "Paracetamol Pediatric Syrup 250mg", category: "Pharmacy", quantity: 1, unitPrice: 110, amount: 110 },
      ],
      subtotal: 480,
      discount: 0,
      total: 480,
      paidAmount: 480,
      paymentMethod: "Cash",
      status: "Paid",
      receiptNotes: "Paid in full at OPD Cash Counter #01. Thank you.",
    },
    {
      id: "inv-2",
      invoiceNo: "ASH-INV-2026-0042",
      patientId: "p-5",
      date: "2026-09-27",
      items: [
        { description: "OPD Consultation – Orthopedics (Dr. Muhammad Kamran)", category: "Consultation", quantity: 1, unitPrice: 200, amount: 200 },
        { description: "Digital Bilateral Knee X-Ray (AP & Lateral)", category: "Lab", quantity: 1, unitPrice: 1200, amount: 1200 },
        { description: "Prescription Medicines (Voltaren, Risek)", category: "Pharmacy", quantity: 1, unitPrice: 650, amount: 650 },
      ],
      subtotal: 2050,
      discount: 1025,
      subsidyNote: "50% Sehat Sahulat Government Health Card Relief",
      total: 1025,
      paidAmount: 0,
      paymentMethod: "Sehat Sahulat",
      status: "Unpaid",
      receiptNotes: "Sehat Card verification pending authorization.",
    },
    {
      id: "inv-3",
      invoiceNo: "ASH-INV-2026-0043",
      patientId: "p-1",
      date: "2026-09-28",
      items: [
        { description: "OPD Consultation – Internal Medicine (Prof. Dr. Muhammad Nadeem)", category: "Consultation", quantity: 1, unitPrice: 200, amount: 200 },
        { description: "HbA1c & Fasting Renal Function Panel", category: "Lab", quantity: 1, unitPrice: 850, amount: 850 },
      ],
      subtotal: 1050,
      discount: 525,
      subsidyNote: "50% KMC Subsidized Welfare Discount",
      total: 525,
      paidAmount: 200,
      paymentMethod: "Cash",
      status: "Partial",
      receiptNotes: "Consultation fee paid; Lab test pending balance Rs 325.",
    },
    {
      id: "inv-4",
      invoiceNo: "ASH-INV-2026-0044",
      patientId: "p-6",
      date: "2026-09-28",
      items: [
        { description: "Emergency Resuscitation & Triage Admission (Prof. Dr. Muhammad Nadeem)", category: "Procedure", quantity: 1, unitPrice: 500, amount: 500 },
        { description: "STAT Dengue Profile (NS1 Antigen & CBC)", category: "Lab", quantity: 1, unitPrice: 950, amount: 950 },
        { description: "Emergency IV Cannulation & Ringer Lactate Infusion", category: "Procedure", quantity: 2, unitPrice: 240, amount: 480 },
      ],
      subtotal: 1930,
      discount: 1930,
      subsidyNote: "100% Emergency & Trauma Welfare Fund (Free ER Care)",
      total: 0,
      paidAmount: 0,
      paymentMethod: "Cash",
      status: "Paid",
      receiptNotes: "Covered under KMC 24/7 Emergency Free Care Policy.",
    },
  ],
};
